### ISSUE TITLE
PostreSQL support

### ISSUE THREAD

**Issue by mkdok** [wodby/adminer#1]
Hello guys. Could you add support PostgreSQL driver for Adminer. Now I don't have possibility t choose from select list another option than MySQL.

Thanks.

**Comment by landsman** [comment]
I want it too pls

**Comment by pprishchepa** [comment]
@csandanov It seems we should download a [full package](https://github.com/vrana/adminer/releases/download/v4.6.3/adminer-4.6.3-en.php) [here](https://github.com/wodby/adminer/blob/master/Dockerfile#L16) instead of mysql version only 
([supported drivers](https://github.com/vrana/adminer/tree/master/adminer/drivers) in adminer).

Also we may install adminer via `composer require vrana/adminer` instead of downloading of compiled version which is har to debug.

**Comment by csandanov** [comment]
PostgreSQL support has some issues outlined in https://github.com/wodby/adminer/pull/2#issuecomment-385180205. We should probably just build pgadmin image

**Comment by landsman** [comment]
Yeah I just used official image.
```
  adminer:
    image: adminer
    restart: always
    labels:
    - 'traefik.backend=adminer'
    - 'traefik.port=8080'
    - 'traefik.frontend.rule=Host:adminer.${TRAEFIK_HOST}'
    depends_on:
    - postgresql
    links:
    - postgresql:postgresql
```
